_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "8":
                - 2
                - 5
            "12": 0.19.7
            "13": linux-x86_64
architecture:
    value: SRCNN
batch_size:
    value: 32
conv1_filters:
    value: 64
conv2_filters:
    value: 32
dataset:
    value: CIFAR10-64
depth:
    value: 10
learning_rate:
    value: 0.001
num_epochs:
    value: 25
optimizer:
    value: Adam
width factor:
    value: 2
